### ISSUE TITLE
[Request] Install Script / Steps to install

### ISSUE THREAD

**Issue by system32uwu** [mehedirm6244/My_XFCE_dotties#5]
First of all I want to say I love your work, all the rices you made look amazing!

I'm trying to get the same looks using the dots you provided in this repo using the [xfce documentation](https://wiki.xfce.org/howto/install_new_themes), so far I got the darknord-gtk-theme applied, but I can't find how to get the bars and the icons you're using, any help is appreciated, thanks in advance.

**Comment by mehedirm6244** [comment]
Hello. Sorry for my late response. Glad you like my rices :smiley: 

## About the panel:
Some plugins have their own unique IDs (such as- Workspace switcher). Let me elaborate:
![image](https://user-images.githubusercontent.com/86041547/151804751-5339dd52-52db-4d25-ad46-c54b82597db1.png)
The code above is for theming the workspace switcher. Notice that I've used `#pager-4` instead of `#pager` or anything else. What does the '4' actually mean here? `pager-4` is actually the ID of Workspace switcher in "my" panel (it's not the same for all). It's very likely that there's a different ID for Workspace switcher of your panel. How do you know the ID?
Well you can use GTK inspector for finding out. Run this on your terminal:
`xfce4-panel -q; GTK_DEBUG=interactive xfce4-panel`
And a lot of windows will pop up...
![image](https://user-images.githubusercontent.com/86041547/151805851-4a5263e7-5931-4687-9153-f62910376fdb.png)

Each of them is for different panel plugins. We only need a specific one of them. But which one?
![image](https://user-images.githubusercontent.com/86041547/151806717-add8a3eb-0ac3-485c-aea8-8adec5aef077.png)
The one which has `XfcePanelWindow` object (as shown above).

![Screenshot_2022-01-31_19-55-28](https://user-images.githubusercontent.com/86041547/151806875-d92483b8-730c-434e-a2dd-9a72f0ae981d.png)
Click the marked icon and hover over the workspace switcher.

![image](https://user-images.githubusercontent.com/86041547/151807174-af8923af-2e30-4f17-8518-bce91ce540a0.png)
If you get similar visual feedback, click on it. You should see something like below:
![image](https://user-images.githubusercontent.com/86041547/151807250-5a935370-577d-4767-ad51-261e5e1e39ed.png)

Now choose 'CSS Selector' like below:
![image](https://user-images.githubusercontent.com/86041547/151807377-d98a7c57-eccd-4584-b963-452a0ce1d06d.png)

You should see something like this:
![image](https://user-images.githubusercontent.com/86041547/151807563-e7009c86-d6c2-44ac-a335-e864a380642c.png)

`widget(pager-4):dir-ltr` From this line, you can tell that the ID of my workspace switcher is `pager-4`. Suppose yours is `pager-12`. Edit the gtk.css file and replace every occurence of `#pager-4` with `#pager-12`. Then exit the debug mode and start the terminal by typing `xfce4-panel & disown`. Now the panel should be good to go

## Icons
I've collected this variant of Zafiro icons from Archcraft linux. You can download it from [here](https://github.com/archcraft-os/packages/tree/main/x86_64). The name of the package is: `archcraft-icons-zafiro-1.0-1-any.pkg.tar.zst`. After downloading it, extract it and copy the icon themes to `~/.local/share/icons`. Now `xfce4-appearance-settings` should automatically find Zafiro icons.

## Installation script?
I don't have any plan for creating an installation script for my dotfiles. There's no guarantee that they'll work out of the box.

**Comment by system32uwu** [comment]
Wow, thank you for the detailed guide and for your time! I think this is enough to get it right. Thank you very much :).
